### ISSUE TITLE
Require pull request reviews before merging

### ISSUE THREAD

**Issue by tdtds** [tdtds/kindlegen#49]
@slonopotamus 

With the introduction of automatic release, review of pull requests has been made mandatory for safety reasons.
Would you assign me as a reviewer when you create a pull request?

**Comment by slonopotamus** [comment]
Okay, no problem

**Comment by slonopotamus** [comment]
I do understand that you don't know me and because of that don't have reasons to trust. Though I may assure you I have only good intents :)

Currently, I have push+release access to:
https://github.com/pygments/pygments.rb
https://github.com/bozaro/git-lfs-java
https://github.com/bozaro/git-as-svn
https://github.com/asciidoctor/asciidoctor-epub3
https://github.com/asciidoctor/asciidoctor-fb2

**Comment by tdtds** [comment]
Of course, I made you a committer because I trusted you!
The purpose of this measure is to reduce the attack surface from malicious third parties. This is what we call "security".
